### ISSUE TITLE
Set width and height other than px

### ISSUE THREAD

**Issue by jop-io** [coddicat/vue-pinch-scroll-zoom#33]
First of all, great component!

I wondering if it is possible to use values for width and height, other than pixels. For example %, vh etc.
```js
<PinchScrollZoom
      ref="zoomer"
      within
      centred
      key-actions
      width="100%"
      height="100vh"
      :min-scale="0.5"
      :max-scale="15"
      @scaling="(e) => onEvent('scaling', e)"
      @startDrag="(e) => onEvent('startDrag', e)"
      @stopDrag="(e) => onEvent('stopDrag', e)"
      @dragging="(e) => onEvent('dragging', e)"
>
    <img src="..." />
</PinchScrollZoom>
```

**Comment by coddicat** [comment]
@jop-io Thanks for the kind words,
Currently, this component is designed to work with concrete numerical values in pixels due to the fact that pixels are extensively used in various calculations within the component, such as setting the origin, translations, determining bounding touch areas, and so forth. 
You can achieve responsiveness or relative sizing by monitoring changes to the parent element's dimensions and then dynamically updating the width and height of this component in pixels. This approach involves adding an event listener for resize events or using a ResizeObserver to watch for changes in the size of the component's parent element. 
I am looking for ways to improve, so we'll take your feedback into consideration for future updates. If there's enough demand for this feature, I may explore more integrated solutions to support relative units directly.

**Comment by jop-io** [comment]
Yes, I suspected this was because of calculation reasons :-)

Using a ResizeObserver is a very good idea and after some fiddling I manage to make it work with just a few extra lines of code.

Thanks for your input, much appreciated!

**Comment by ShadowSpade** [comment]
Heyo, @jop-io  would you please share some of that code? I also need dynamic sizes and am struggling to get it to work

**Comment by coddicat** [comment]
@ShadowSpade Hi, is that still relevant?

**Comment by ShadowSpade** [comment]
I had some trouble yes, but ended up going with a different package because I had some other requirements as well that needed to work with a zoom package
