### ISSUE TITLE
centred not aligning image centered

### ISSUE THREAD

**Issue by joingenor** [coddicat/vue-pinch-scroll-zoom#34]
I am using this plugin in my project and have set these props
    within
    centred
    key-actions
    :width="390"
    :height="300"
    :min-scale="1"
    :max-scale="10"

Image is rendered like this and not centered
![image](https://github.com/coddicat/vue-pinch-scroll-zoom/assets/3841752/5bdb8ba0-b07d-49db-ad77-52e530eb9d8a)

**Comment by coddicat** [comment]
Hi @joingenor,
I need a bit more context to provide you with an accurate and helpful response. Could you please share the HTML and CSS code snippets where you're attempting to use this component?

**Comment by joingenor** [comment]
**HTML**
<div class="v-responsive__content"><div data-v-84446679="" style="align-items: center; height: 100%;"><div data-v-810ea06a="" data-v-84446679="" class="sliderImage" style="width: 100%; height: 100%;"><div data-v-810ea06a="" class="pinch-scroll-zoom" tabindex="0" disable-pan="" auto-zoom-out="" disable-zoom-control="disable" limit-zoom="10" style="width: 390px; height: 300px;"><div class="pinch-scroll-zoom__content" style="transform: translate3d(0px, 0px, 0px) scale(1); transform-origin: 195px 150px;"><img data-v-810ea06a="" alt="loaded-image" height="100%" style="object-fit: cover; margin: auto;" src="/seebritejib/api/file/f9213723-0196-499e-8c73-72b5d83b10b0/medium"></div></div></div></div></div>

**Comment by coddicat** [comment]
@joingenor 
You've shown me the compiled HTML, which doesn't make anything clear. Send me the Vue source code, how you integrate the component on your view. The more you provide, the better, preferably with CSS (or preprocessing).

**Comment by MrMarble** [comment]
I'm having a similar problem, the image is not centered, and also the zoom does not apply where I try to zoom but on the left side.

Here's the code, I want to fill the whole screen, that's why I use the `zoomable` ref, to get the parent with/height dynamically
```vue
    <div ref="zoomable" class="w-full flex-grow bg-gray-100">
      <PinchScrollZoom ref="zoomer" :width="width" :height="height" centred within>
        <img :src="image" alt="boulder" :width="width">
      </PinchScrollZoom>
    </div>
```

<details><summary>Screenshots</summary>
<p>

![imagen](https://github.com/coddicat/vue-pinch-scroll-zoom/assets/4268580/678dea21-82e7-4115-870c-228b8c181592)
![imagen](https://github.com/coddicat/vue-pinch-scroll-zoom/assets/4268580/27903a2a-fa3f-4fbc-a515-de47555d4867)
![imagen](https://github.com/coddicat/vue-pinch-scroll-zoom/assets/4268580/55df4fb1-2bfc-4d40-8422-32d57c998564)
</p>
</details> 

As you see, the "pinch zone" fills the screen but the image is on the left side, also trying to zoom keeps the image attached to that position as well (last screenshot)

**Comment by coddicat** [comment]
@MrMarble 
component is designed to work with static, numerical values for its width and height properties. These properties define the bounds of the visible area, and all scaling and positioning calculations within the component are referenced to these properties, using pixels as units. This design choice is due to pixels being extensively used in various calculations within the component, ensuring precise control over the zoom and positioning functionalities. 
To achieve dynamic resizing while maintaining the functionality of the component, I recommend implementing a ResizeObserver on the zoomable div.

**Comment by MrMarble** [comment]
> @MrMarble 
> component is designed to work with static, numerical values for its width and height properties. These properties define the bounds of the visible area, and all scaling and positioning calculations within the component are referenced to these properties, using pixels as units. This design choice is due to pixels being extensively used in various calculations within the component, ensuring precise control over the zoom and positioning functionalities. 
> To achieve dynamic resizing while maintaining the functionality of the component, I recommend implementing a ResizeObserver on the zoomable div.

Is a mobile web app, once rendered the div is not going to be resized but I need the initial width (that matches the screen width), I'm using the vueuse useElementWidth composable to get the `zoomable` width

**Comment by coddicat** [comment]
@MrMarble It would be much easier to figure it out if you could send a link to a fiddle or the source code, so I could play around with it.

**Comment by MrMarble** [comment]
> @MrMarble It would be much easier to figure it out if you could send a link to a fiddle or the source code, so I could play around with it.

I made this demo https://stackblitz.com/edit/vitejs-vite-7u8bkm?file=src%2Fcomponents%2FZoomable.vue&terminal=dev
> Stackblitz works best on Chrome, in Firefox you need to open the preview on its own tab

**Comment by coddicat** [comment]
@MrMarble, Thanks, I've resolved the issue you encountered, look at the updated demo: 
[https://stackblitz.com/edit/vitejs-vite-5jtnhc?file=src%2Fcomponents%2FZoomable.vue&terminal=dev](https://stackblitz.com/edit/vitejs-vite-5jtnhc?file=src%2Fcomponents%2FZoomable.vue&terminal=dev)

Here’s a brief explanation of the key changes:

1. Dynamic Size Handling:
```javascript
watch([w, h], () => {
  visible.value = false;
  nextTick(() => (visible.value = true));
});
```

Initially, the width and height of the zoomable element are set to zero because the element hasn't been mounted or rendered yet. When the component is eventually mounted or its size changes, we need to forces a re-render, allowing the component to accurately calculate and set the proper positions of the content based on its actual size.

2. Position Calculation:
It’s important to provide the component with content-width and content-height properties. These properties are essential for the component to accurately calculate the positioning of the content within the zoomable area.

3. Styling Conflict Resolution:
The parent element had text-align: center; applied, which unexpectedly affected the zoomable element's behavior. This was an oversight on my part, and I plan to address it in the next version of the component. For a temporary fix, you can add text-align: initial; to the zoomable element's styles to prevent the parent's text alignment from affecting it.

**Comment by coddicat** [comment]
@MrMarble I will review the documentation soon
